### ISSUE TITLE
Add a chronometer to mobilito recording

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#1006]
I think that a chronometer is a good way to know how long you've been recording and can help toward recording longer sessions if coupled with a "goal" bar. 

Say we set a bar that fills in 5 minutes with an indication that it would be nice if you reached that point ?

**Comment by Shriukan33** [comment]
What about simply adding the chronometer for now ?

**Comment by Shriukan33** [comment]
Maybe filling another bar on top of the other could achieve the desired effect, like first bar is green, second yellow, last red-ish 
All those with some text that cheers for more.

**Comment by JeffAbrahamson** [comment]
We might want to test with coloured pencils on paper first.  It's way faster. ;-)
