### ISSUE TITLE
Permit mobilito users to modify their location data

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1022]
For a period of, say, a week after creating a session, permit a user to modify the location field.  Do this the way github does for issue subjects.

**Comment by Shriukan33** [comment]
Maybe we could do this from the session summary, with a button?

**Comment by JeffAbrahamson** [comment]
> Maybe we could do this from the session summary, with a button?

Sorry, had missed a key word in the subject line, indeed.

**Comment by Shriukan33** [comment]
Question, what's the goal behind the time limit? Why not allowing older than a week sessions to be updated?

**Comment by Shriukan33** [comment]
> > Question, what's the goal behind the time limit? Why not allowing older than a week sessions to be updated?
> 
> Maybe it's silly. I'm inspired by sites like SO that don't let you change comments after too much time has gone by (there: 5 minutes), which is different. But if you come back a month later and propose to change your location data, do you _really_ likely remember the details?

It's an easy to remove constraint anyway, we can let that be for now.
