### ISSUE TITLE
Simon suggestions

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#103]
From mail on 26.02.2021:

* the favicon is not set
* there isn't many social buttons on that website!
* you don't have the ".com"? 
* generally, you've tried to fill all the space. Don't be afraid to leave empty space between things, it makes things more quiet and easier to read.

[simon-comments.pdf](https://github.com/transport-nantes/tn_web/files/6137048/simon-comments.pdf)

**Comment by JeffAbrahamson** [comment]
Make test respect colours in visual identity.

**Comment by JeffAbrahamson** [comment]
Is this closable ?

**Comment by Shriukan33** [comment]
> Is this closable @Shriukan33 ?

Yes, favicon is added, socials as well, we gave some space but there is still work to be done on the front side, on spaces mostly.
Gaelle gave me a list of things to correct but stripe became a priority in the meantime. Also most of the work is done.

**Comment by JeffAbrahamson** [comment]
Want to maybe make new issues for what's left and then close this one?  Really old issues tend to stagnate if they're not refreshed.  Refer to this issue in the new one, of course.
