### ISSUE TITLE
Fix press release publication constraints

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1041]
Providing a header title without header description fails publication test, but a title without description appears perfectly acceptable.

In addition, if there's no header image, neither are even displayed, and yet this blocks publication.

---

In addition, I see this:
```
Éléments manquants pour la publication : header_title, header_image, 
```
(Note the trailing empty element in the three element list.)

And yet, those elements are all present:
![image](https://user-images.githubusercontent.com/1220683/205151043-b96be6b3-d17b-4d79-b913-e0d6e965fbdb.png)

**Comment by JeffAbrahamson** [comment]
Adding an image permits publication, but in this case I didn't want an image!

**Comment by Shriukan33** [comment]
`header` title and descriptions are these : 
![image](https://user-images.githubusercontent.com/70256364/205653821-f7e15717-8abf-42d3-bfc7-e3dc494610ba.png)

So they need an image to be valid. 
Setting them without an image makes no sense. 

What did you want to set by providing those values ?

**Comment by Shriukan33** [comment]
I think there was a misunderstanding, closing for now.
