### ISSUE TITLE
photo gallery: index page has low expectations (only 4 photos)

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1047]
The main gallery restricts itself to only four images.  This is rather Lilliputian of us.  Can we find any argument not to set the limit to 20?

**Comment by JeffAbrahamson** [comment]
> Could be loading time for the first page, but sure we can bump this up!

[This page](https://www.nhm.ac.uk/wpy/gallery) loads pretty fast.  What do you think they are doing that we can't?

**Comment by Shriukan33** [comment]
They load 4 images at the time, it's like infinite scrolling.
I did look into it, but I found no easy way to implement it, so I dropped it.
