### ISSUE TITLE
photo gallery trailing issues

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1051]
## Important

* [x] #1045 
* [x] #1046 
* [x] #1047 
* [x] #1048 
* [x] #1052 

## Release blocking

* [x] #1049
* [x] #1050 
* [x] #1054

**Comment by Shriukan33** [comment]
Updated topic with today's PR for project management

**Comment by JeffAbrahamson** [comment]
Please use the comment facility rather than adding comments to the punch list at the top.  That makes it hard to read and hard to track.

**Comment by JeffAbrahamson** [comment]
P0, 8d old, 3/8 tasks remaining.  Status?
