### ISSUE TITLE
photo galerie 404's if no images

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1052]
`/photo/galerie/`

**Comment by Shriukan33** [comment]
I only have an empty list : 
![image](https://user-images.githubusercontent.com/70256364/205689110-f3d19e97-f133-4b01-a4e0-f49bd7ef561d.png)

**Comment by JeffAbrahamson** [comment]
That's what I see on production today.  Good, it doesn't 404.

I'll argue it's still a bug to say "here are all the photos" when there are none, even if the empty set is correctly the result of all on the empty set.

The phrase itself ("Toutes les photos ... préférées !") should assuredly be deleted, it's in the category of "this is a door, you can use it to go to the next room". ;-)

**Comment by Shriukan33** [comment]
> That's what I see on production today. Good, it doesn't 404.
> 
> I'll argue it's still a bug to say "here are all the photos" when there are none, even if the empty set is correctly the result of all on the empty set.

Will add a fallback, but we generally don't want to share a gallery without any content haha

> The phrase itself ("Toutes les photos ... préférées !") should assuredly be deleted, it's in the category of "this is a door, you can use it to go to the next room". ;-)

Hmm, I think that although it's obvious, it's a push in the right direction to suggest 'you definitely should vote' ! Do you really want to get rid of it ?
