### ISSUE TITLE
Add mobilito map in summary emails

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#1062]
I did some research about how to go from lat/lng tuple to rendered png, there are services that provide that but it looks quite complex and long for that purpose.

https://print.get-map.org/about/api/
https://github.com/hholzgra/ocitysmap/

Or maybe having a tile render server of our own
https://github.com/enzet/map-machine#tile-server

There is no easy way if we want to add that into emails, I think.
Maybe we should encourage clicking to discover more info about the session, instead of trying to render it before sending. That would be much simpler implementation wise, not sure this is worth the hassle.

What do you think ?

**Comment by JeffAbrahamson** [comment]
* [SO / tilemill](https://stackoverflow.com/questions/15623509/python-what-is-the-best-way-of-creating-a-png-of-a-map-with-a-route-for-a-writt)
* [ipyleaflet](https://stackoverflow.com/questions/44800396/python-ipyleaflet-export-map-as-png-or-jpg-or-svg)
* [py-staticmaps](https://pypi.org/project/py-staticmaps/)
