### ISSUE TITLE
the photo gallery image pages are missing a way to get back to the gallery

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1086]
We'd like to encourage sharing, not just sharing of single images.

It's also quite common that people click down, then go back up to select a different images.

**Comment by Shriukan33** [comment]
I don't understand this issue ?

**Comment by JeffAbrahamson** [comment]
> I don't understand this issue ?

If you're at `galerie/1234ab`, how do you get back to `galerie/` without manually editing the URL?
