### ISSUE TITLE
the photo entries admin page could benefit from an "accepted" status filter

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1088]
Note, too, that the flag hides itself if the window isn't wide enough.  Though seeing a little flag isn't the same as reducing the selection to only selected photos.

**Comment by Shriukan33** [comment]
![image](https://user-images.githubusercontent.com/70256364/209929580-8cfd5901-bea9-4d26-9474-77e07ac6baaf.png)

What's the difference with this?

**Comment by JeffAbrahamson** [comment]
> ![image](https://user-images.githubusercontent.com/70256364/209929580-8cfd5901-bea9-4d26-9474-77e07ac6baaf.png)
> 
> What's the difference with this?

Ah, indeed, nothing!  It's just that it was at the end of a 1000 or so email addresses just above, and I missed it. ;-)
