### ISSUE TITLE
Add introductory text to photo gallery

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1091]
cf. https://docs.google.com/document/d/1L-xxNrBYuDR3l-8J2rI-4Iw56gQXRm_PPvWzoDzmCOU/edit#

**Comment by Shriukan33** [comment]
I added a page that displays your text (modulo some formulations), I think it needs highlights to catch the eye. It's a wall of text.

![image](https://user-images.githubusercontent.com/70256364/211511127-c485e1a2-b7cd-4700-a3d9-64764baa0b3c.png)

So I picked up *Refactoring UI* and went on the font part to see if there is anything I could do to help.

The book recommends lines no longer than 75 chars, which is on desktop a col-4 (1/3 of viewport's width)
Also, the longer the line, the higher the line height should be. Especially if the font is small.

I'd say we have a pretty standard size, so I tried to bump it to 1.75, and it feels quite nice, although it's no major difference.

To compare, lemonde.fr has 70 char on one line and a line height of 1.55 with a bit bigger font-size.

I tried to justify with hyphens to give it a more "print" feel as it's a formal communication, but it didn't feel vastly different or better. 

I'm not sure how about how to make it catch the eye a bit better, but right now, I don't think it's very appealing, format wise. 

Here is the line-height increased version : 

![image](https://user-images.githubusercontent.com/70256364/211518573-4dc0ad94-7c6e-45ef-a399-f8e118e38077.png)
