### ISSUE TITLE
Add reasonable og data to photo gallery images

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1093]
Requires #1092 if we intend to use something from the description (which is surely logical).

**Comment by Shriukan33** [comment]
the description in our case would be what field ? `pedestrian_issues_md` or `submitter_info_md` maybe?

**Comment by JeffAbrahamson** [comment]
I think `pedestrian_issues_md` is the right source, since it's under our control.  The photographer's comments are not always suitable (to short or too technical).
