### ISSUE TITLE
Determine plan for publicising photo gallery

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#1094]
What still needs to be done?

Once we start publicising it, many things that would be just sort of urgent now will become crushingly "must be sorted now" urgent.

**Comment by Shriukan33** [comment]
We should set legit looking on beta and ask a handful of people to try to use it on beta, getting some feedbacks, probably. 
The app being used by people that aren't us could have some interesting effects, I could probably ask some folks, it's easily doable.

For now it seems to be usable, you have a global list, all pages are responsive, you can like any pic that is accepted, and share on social medias. The basic features are there, but as devs, we're not as naive as the other toward this app, we have the dev filter on our mind.

I say let's see what non devs have to say about it.

**Comment by JeffAbrahamson** [comment]
The photo project is now completed and considered at EOL.
