### ISSUE TITLE
Photo gallery hits short cycles

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#1096]
When clicking next repetitively (for instance, 3 times), the gallery loops over the two same pictures unless you click on previous.

It seems to be coming from the function that sets the next and previous links.

**Comment by Shriukan33** [comment]
This doesn't happen in local on the same sha1

**Comment by JeffAbrahamson** [comment]
Looks like we're not testing the prev/next endpoints, either.

**Comment by JeffAbrahamson** [comment]
@Shriukan33 I've pushed a branch that I claim probably sorts this issue.  I need to write better tests, so I've not yet requested review.  That said, feedback always welcome.
