### ISSUE TITLE
Add a "my sessions" page for Mobilito

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#1101]
If you want to find all your sessions, you have to keep the email, or chances are you're never going to find the URL again.

Let's say you want to show someone the session you did the other day, you have no easy way to do so.

wdyt?

**Comment by JeffAbrahamson** [comment]
Yes.

Isn't there an issue somewhere to make a vigilo-like or strava-like feed of recent counts?  There should be.  Non-counters should be able to see things and be motivated (or not).

**Comment by Shriukan33** [comment]
Where would that feed be? This warrants a different issue (this one is for one's sessions).

How would that be presented ?

**Comment by JeffAbrahamson** [comment]
Have you played with the strava feed?
Have you played with the vigilo feed?

**Comment by Shriukan33** [comment]
Doesn't mean we should apply 1 to 1 any of those :)

I mean, if you suggest it, maybe you have some key features you think fit mobilito and would add something.

Mobilito isn't a social network, initially, but a tool.
Introducing a feed has many implications in my mind, that would make the complexity blow, I'm not entirely sure to know what Mobilito is supposed to be anymore.

**Comment by JeffAbrahamson** [comment]
Vigilo isn't a social network, either.  Have you looked at its feed?  It's pretty rudimentary from a UI standpoint, but it exists and is one way we could inspire ourselves.

**Comment by Shriukan33** [comment]
![image](https://user-images.githubusercontent.com/70256364/210085457-5d21538b-bee4-4e41-89a9-4e7878ef5544.png)

![image](https://user-images.githubusercontent.com/70256364/210085479-fbabaf50-5473-4a51-8a9b-72bf618b5166.png)

Yup, I can see something like this Mobilito themed with a chart instead of picture, and a quick description (location and date, in the same fashion)

Strava however, is very different and is kind of a social network.

**Comment by JeffAbrahamson** [comment]
I honestly don't see why the strava feed doesn't fit into mobilito.

But at the moment we have zero discoverability, so anything is better.

![image](https://user-images.githubusercontent.com/1220683/210086481-7181b0f6-160d-4d42-a417-840e29e1c521.png)

**Comment by Shriukan33** [comment]
Strava's key differences : 
Custom feed per user, comments and "kudos", various pics attached (mostly maps but not necessarily), you can sub to challenges, see each other's profiles and histories...

Vigilo keeps it simple by providing a "latest submissions" that is easy to parse and mostly just informative, you don't actually have interactions with it.
