### ISSUE TITLE
Make MVP of Observatoire du Velopolitain

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#118]
This is higher priority than #116.  We just need something that displays the main page with the map.  Since this will be part of our django app, we don't need to worry about any of the other menus or footer things: just diplaying the map with an appropriate title.  The thermometers can be replaced with text: "avancement de X : 0 %" etc.  We'll fine-tune after.

The code for the hacked up version that we're running [here](https://nantes-velo.p27.eu/) is in [github here](https://github.com/transport-nantes/planvelo).  The map is in [this repo](https://github.com/transport-nantes/planvelo-carte/).  It is not at all desirable for us that the thing be split across two repos, but for the moment we can leave the map in the plan-carte repo.

The goal of this issue is to make something non-interactive that simply displays Clément's map (planvelo-theorie.geojson).  We want to put a stake in the ground and say "we're on this".  The rest we can follow along with afterwards.

**Comment by JeffAbrahamson** [comment]
La définition du MVP évolue :
* Plus de mention de PeS sauf dans le code (dans le mesure où il y a du code d'origine qui reste)
* La carte des aménagements à jour
* Les distances calculees
* Les pourcentages et barres de progression à jour (ou chiffres de progression si besoin)
* Les filtres sur les niveaux hiérarchiques
* Les différents textes finalisés

CC s'occupe de la partie carto.

**Comment by JeffAbrahamson** [comment]
# Status update

We have a candidate MVP deployed on beta.  A few things remain.

## Tech things

* Clean up commits,   Squash the requirement.txt commits together so it changes only once for good form.  Use good commit messages -- [example-0](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html) [example-1](https://hackernoon.com/git-it-together-some-tips-on-commit-etiquette-and-best-practices-for-junior-developers-1f147b8dfd56) [example-2](https://thoughtbot.com/blog/5-useful-tips-for-a-better-commit-message) [example-2](https://chris.beams.io/posts/git-commit/)
* Fix the path so that it's `/observatoire/nantes/velopolitain/` or `/observatoire/nantes/planvelo/`, with the second element as a `<string>` arg passed to the view.
* The view should auto-discover all layers for the city (better: location) provided.
* We shouldn't write that file with `m.save()`.  For one thing, imagine we have `.../bordeaux/...` and then the files conflict (race condition).  Inventing a clever naming scheme is not the right response. ;-)  Remember that this is python, and so you have the source code for `save` in your venv.  How is `save()` implemented?  What can you learn there?

**Comment by JeffAbrahamson** [comment]
@Shriukan33 Let's make a clear list of what needs to be done to close this issue, then make new issues for what doesn't need to happen immediately and then close this one once the branch is merged.

Can we fix the html, say by using the django module that wraps folium?  The page looks a bit shit on mobile, I think because of the goofy html structure.

**Comment by Shriukan33** [comment]
I can use my newly developed skills to see how I can make this more responsive for the map part. 
The navbar looks a bit bigger, and probably we're going to need to modify some parts of follium. 
I haven't identified the source yet, going to investigate. 

Maybe adding layer groups could also be a valid point, as there are numerous layers this isn't the most comfortable for users, I'd say. 

Once this is done I think this could qualify as a decent MVP 

What do you think ?

**Comment by JeffAbrahamson** [comment]
Sounds good.  You've looked at the html of the page?  It's absolutely insane and (I think) not valid.

```
<!DOCTYPE html>
<html lang="fr">
<head>...
<!DOCTYPE html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
...
</head>
<body>
<div class="folium-map" id="map_b0d836bc9b804a4cab79b351097f08c3"></div>
</body>
<script>
...
</script>
</div>
...
</body>
</html>
```
