### ISSUE TITLE
Integrate gaelle's design 

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#174]
Closes #103 

There is still some work to do on spaces. 
Buttons are not rounded. 
Blue background to be added
Banner should take the whole width 

Reference : 
 
![image](https://user-images.githubusercontent.com/70256364/129529270-a26da465-cc41-4fad-90cf-23076d4606d7.png)

**Comment by JeffAbrahamson** [comment]
Is this done?
