### ISSUE TITLE
Record name on donation

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#178]
When creating accepting a donation, whether the user is new or old, if the first and last name are blank, we should fill them in with the name provided at donation.

If _either_ has been provided by the user, we should respect that and not modify them.  (And we should comment in the code that this is intentional.)  This avoids things like saying that my name is Joe but I make a donation as Joseph Biden and suddenly I'm greeted as "M Biden" or "Joseph" when I clearly said I'm "Joe".

___

Benja Edit to remember how we suggested this should happen : 

```
def name_if_unnamed(self, firstname, lastname):
    """Name user if unnamed.

    If the user has no first or last name, provide them.
    If either exists, however, we should respect them.

    This is for instances where the user provides a name without
    meaning to edit her/his user profile.  For example, if the user
    intends to be called "Joe", we shouldn't take a legal name
    attached to a bank card and start saying "Hello, Joseph".
    """
    if self.user.firstname or self.user.lastname:
        return
    self.user.firstname = firstname
    self.user.lastname = lastname

```

+ Tests

**Comment by Shriukan33** [comment]
First and last name are required to go through the form. 
The name we save is the one given in the form, not the one on the credit card. User can enter Joe if it wants. 

I'm not sure to understand what you want to change ? Do you want to make the fields optional ?

**Comment by JeffAbrahamson** [comment]
After making a donation, we have a valid user object.  Maybe we just created it, maybe we pulled it from the db based on the user's email, maybe the user was already logged in.

If the user object is missing first _and_ last name and the donation form provided the missing data, fill them both in on the user object.

Otherwise, leave the user object alone.
