### ISSUE TITLE
Why is static failing in dev?

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#188]
I suspect that this is a settings issue, and so specific to each dev.  In that case, we should update `settings_local.py.DEV.template` to be correct for static and media so that we all can know an example of something that works.

**Comment by Shriukan33** [comment]
Can't reproduce, suspect it is static_url in settings_local.py that is faulty : 
https://github.com/transport-nantes/tn_web/commit/7595bff37e0f7e5ec9f942f31a56c9cfc727e27f
