### ISSUE TITLE
Use whitenoise?

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#191]
As [discussed](https://github.com/transport-nantes/tn_web/issues/115#issuecomment-903142553), we should have different images upload with different prefixes, and we should offer suggestions of the image sizes we expect.

One way that might make quite a lot of sense would be to use [whitenoise](https://whitenoise.evans.io/en/stable/django.html).  Stop after step 3 -- i.e., don't even think about using a CDN except, like, late at night or something. ;-)

For example, twitter cards would upload with a prefix of "twitter-card" and a suggestions of (say) 1200x628 with a [link](https://business.twitter.com/en/help/campaign-setup/creative-ad-specifications.html) for easily finding more info.

Let the image suggestions be todo items for now unless you find them quickly.

**Comment by Shriukan33** [comment]
I'm not sure to understand what problem is solves ? 
From the RTD : 

> With a couple of lines of config WhiteNoise allows your web app to serve its own static files, making it a self-contained unit that can be deployed anywhere without relying on nginx, Amazon S3 or any other external service. 

So it would serve statics using Django instead of the server ? Why do you want to cut nginx ?

**Comment by JeffAbrahamson** [comment]
If that's it, I've misunderstood.

What I understand is that it helps at upload time so that we can let people choose files already uploaded.

**Comment by JeffAbrahamson** [comment]
OK, I misunderstood.  I'm going to close this, then.

What I want is something so that we can re-use uploaded content.  It's not urgent.
