### ISSUE TITLE
Get SES working

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#199]
We use Amazon SES for mail.

TODO:
* [x] @JeffAbrahamson gives @Shriukan33 AWS access to admin
* [x] @Shriukan33 gets "thank you for your donation" mails working, cf #49 when starting to send mail
* [ ] @Shriukan33 consults with GJ on text of said mail so that we all agree.  That mail should be a TBv2 item with "view on web" link.

**Comment by JeffAbrahamson** [comment]
In making mail work, we'll also want to make newsletters work, which means TBv2 integration.

**Comment by Shriukan33** [comment]
Added :

- [ ] Add mobilitains.fr as verified domain to send mails from in AWS. See https://us-east-2.console.aws.amazon.com/sesv2/home?region=us-east-2#/verified-identities

**Comment by Shriukan33** [comment]
We don't send emails on donation, only show a template : 
https://github.com/transport-nantes/tn_web/blob/a8a8cceb4ece8d3810ac255607881da2c7302684/transport_nantes/stripe_app/views.py#L205-L210

**Comment by JeffAbrahamson** [comment]
That's what I thought.  And yet this issue has been 0-urgent since 2021-11-21...
