### ISSUE TITLE
Avoid putting logic in javascript unless there's no other way around it

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#210]
At lines 250 ff of `transport_nantes/stripe_app/static/stripe_app/form_flow.js`, you set the originating view and parameters of the form.  But those values are available to the view in django and so can and should be set there.

This makes the code more readable and easier to debug.  Pushing logic client-side makes debugging much harder when something goes wrong.

**Comment by Shriukan33** [comment]
When the webpage calls for the create_checkout_session function through fetch, how do I know, through the request.POST, what view has been used to create the page ?

**Comment by JeffAbrahamson** [comment]
When the user starts the checkout process, you can use `reverse` to get the path.
Set that in the context.

**Comment by Shriukan33** [comment]
So we moved some logic to django with the introduction of originating_view in the View context, anything else you want to move in this issue ?

**Comment by JeffAbrahamson** [comment]
Is there a reason at line 85 that we need to insert the sentence and not just the amount?  I.e., why not put the amount in a span with its own id so you can just set that?

Similarly, at line 162, it's good that the amount is in a  span, but the point of that would mostly be to push the span to the template and just manipulate the amount and maybe the visibility of the line via javascript but not the phrasing.

One of the objectives of django's separation of logic and presentation is that different people with different skills can edit different parts.  So imagine we had the manpower to have someone who's good at composing text improving our templates.  But you're mucking with the text itself in the javascript.

Similarly, suppose you see the word "le montant de votre don" on a page and you grep for where this occurs.  Unless you think to grep through the js, you'd not find it.  Of course, you'd grep through the js and the py once your grep across html files failed, but the text should be in templates.

In a further case (that we don't have, but that underlines the reasoning for having these things separated, suppose, like Jellybooks, that you present in several languages.  The javascript changes the amount and maybe the currency symbol and position based on locale, but the text is handled by `gettext`.
