### ISSUE TITLE
ajax template list view doesn't init on initial page display on firefox

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#232]

**Comment by JeffAbrahamson** [comment]
At [this page](http://localhost:8000/tb/admin/new/#) I see this:

![image](https://user-images.githubusercontent.com/1220683/137773270-8e1cc93c-51a2-4f78-9311-9c01c5222eb3.png)

Note that the template has no default value, nor does content type.  But I do have an existing template.  That shouldn't happen.  (Indeed, where does the string "-----" even come from?)

I've run `collectstatic` and done a shift-refresh in my browser.  I can see in the django dev server log that the file `/static/topicblog/update_template_list.js` is being fetched.

What do you see?

**Comment by JeffAbrahamson** [comment]
Is this sorted in all major browsers (chrome, firefox, safari on desktop and on mobile, at the very least)?

**Comment by Shriukan33** [comment]
Yes, only requirement is Ajax, which is compatible with any modern browser. Also allowing dropdown lists, but this is fine as well
