### ISSUE TITLE
Make sure that stripe webhook processes recurring donations

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#233]
Need to make sure that the webhook handles recurring donations so proper history is kept.

**Comment by Shriukan33** [comment]
it appears the next donation didn't get catch, need to investigate the why

**Comment by JeffAbrahamson** [comment]
What do the logs reveal about what happened when the webhook was called with the missed recurring donation?

**Comment by JeffAbrahamson** [comment]
It looks like [this payment](https://dashboard.stripe.com/payments/pi_3JvlvdClnCBJWy550HjbEn4N) on 14 November 2021 17:51 failed without leaving a trace in our logs.

Then [this payment](https://dashboard.stripe.com/payments/pi_3JxckkClnCBJWy551VJtp4Wd) succeeded.  The only trace I see in our logs is this:

```
127.0.0.1 - - [19/Nov/2021:19:28:10 +0000] "POST /donation/webhook/ HTTP/1.0" 200 0 "-" "Stripe/1.0 (+https://stripe.com/docs/webhooks)"
```

I don't see any useful logging about any of our donations.

**Comment by JeffAbrahamson** [comment]
What is the status of this issue?

**Comment by Shriukan33** [comment]
I configured the webhook to send the events, so we should see the code work now, it was on Stripe's dashboard end. However, the cli doesn't allow us to reproduce the events, so not able to testify that it will work.

**Comment by JeffAbrahamson** [comment]
In this case, the procedure is
* put a reminder in your calendar for when you expect the next event to occur
* note here when your reminder is
* on that day, update here with what happened, even if the update is "nothing on stripe dashboard yet, will update tomorrow"

**Comment by Shriukan33** [comment]
![image](https://user-images.githubusercontent.com/70256364/144458409-b64e5f1b-4b68-4b5c-b25e-5d3972b79b5c.png)

Monday 20th of December we should have the next occurrence

**Comment by Shriukan33** [comment]
Recurring payment happened yesterday on our Stripe Account, didn't register on our side. Needs further investigation about why.

**Comment by JeffAbrahamson** [comment]
We need for this to stop, too.  So some things you should do:
* Can we test this on beta with stripe's test mode?
* Every path through the donation code should provide enough logging information that we know what's happened later.  We can't have donations happen and wonder how they were processed.  For example, we know that the event was received and dispatched, but we still don't know what happened.  That's not ok.
* Given that this is still an issue, when you get a payload from stripe, pickle it and dump it to disk before doing anything else.  That way you can debug it later if you have to.  When dumping to disk, make sure you have the right to write to the directory where you dump it.  Make sure you set perms to 0x400 to reduce PII concerns.  Ideally, the directory itself should be 0x700.

**Comment by Shriukan33** [comment]
Found that we can actually resend events through Stripe's Dahsboard : 

![image](https://user-images.githubusercontent.com/70256364/147118326-e78a81c5-8f84-441b-886a-85fb1da3f95c.png)

So this is the optimal way to test our implementation. 

Logs implemented have shown that the problem with out current reccurring payment is that the creation of the subscription is anterior to the point where we saved stripe customer ID. 
This makes the save_recurring_payment_details() function not saving its current plan as donation, because it can't find the needed details : 
https://github.com/transport-nantes/tn_web/blob/0ac82486b8da9aa484e8e75d8f20096479498e6c/transport_nantes/stripe_app/views.py#L459

Saving the customer ID allows us to match the details saved on the original checkout with the recurring event. 

My solution for the already running subscriptions would be to update the donation record made at the very beginning and add the customer number into the field in the database.

**Comment by JeffAbrahamson** [comment]
SGTM

**Comment by JeffAbrahamson** [comment]
Somehow we'll want to make sure we don't record events more than once, now that we know they can be received more than once.

**Comment by JeffAbrahamson** [comment]
SGTM

**Comment by JeffAbrahamson** [comment]
Be sure to document what you are doing with targeted links to the stripe docs so that if there's a question down the road, we can all (including you) reproduce your reasoning.
