### ISSUE TITLE
TBv2 variant creation

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#240]
On editing a TBItem, we should _always_ (unless the item is new) offer to create a variant.  After a configurable period of time (let's put it in `settings_local` for now, we'll set to 12 hours in prod but devs might have other needs) the only option is a variant.

Variant means same slug but otherwise same content except what the user has changed.

Note that this is from publication time.  Before publication, changes are fine.  After publication, the slug should no longer be modifiable.

We should also offer an option to make a copy.  The only difference between copy and variant is that a copy permits a new slug whereas a variant does not.  But that means that copies are variants if the user doesn't change the slug.

**Comment by JeffAbrahamson** [comment]
The (global) settings variable `EDITING_TIME_IN_HOURS` has a very non-global sense.  In addition, it isn't really the amount of time you can spend editing but the amount of time before you may no longer edit.

It's generally helpful to give things like this names and then to use those names everywhere.  It makes code and the conceptual model it is implementing clearer to readers and easier to discuss.

Finally, it's helpful for readability and not making coding mistakes to identify the units of constants and variables that have units.  And just as cosmologists measure the universe in cm, computer programmers generally measure the world in seconds (except when more precision is needed, and then we use microseconds or nanoseconds).  Why?  Because the day you are doing development and have to set the field to 1/60 or 1/3600 only to discover that somewhere something bugs on getting a floating point number.  And this is why we should have handy constants like `SECONDS_IN_MINUTE`, `SECONDS_IN_HOUR`, and `MINUTES_IN_HOUR`.

Perhaps call it `TOPIC_BLOG_EDIT_WINDOW_SECONDS` ?

**Comment by JeffAbrahamson** [comment]
I think we should always maintain the option to create a variant.  It is the option to modify that closes.

**Comment by JeffAbrahamson** [comment]
Please rebase and correct conflicts on be13515.

**Comment by Shriukan33** [comment]
Solved merge issues, also changed the name of the CONST, it lacked context I agree.

**Comment by JeffAbrahamson** [comment]
Is this closable @Shriukan33 ?
