### ISSUE TITLE
Create a publish button (URL for now)

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#241]
We need a URL that permits publishing a TBItem.  It requires a slug and a pk id as arguments.

It should validate that all fields that the template description says are required are actually present.  Since that functionality isn't present, we just need to leave comments in the code about where we intend to put it, and then verify that things that really are mandatory everywhere (slug, title, etc.) are satisfied.

**Comment by JeffAbrahamson** [comment]
For now, access by explicit URL, restricted to admin.

**Comment by Shriukan33** [comment]
@JeffAbrahamson Do you think it's done ? As you merged the branch I'm tempted to say yes, but maybe you have another say to add ?
