### ISSUE TITLE
Progressively remove TBv1 code

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#256]
# Phase One

In this issue we want to start by removing this line from `topicblog/urls.py`:
```
    path('s/<slug:item_slug>/', TopicBlogItemView.as_view(),
         name='view_item_by_slug'),
```

The ramification of that is that we will invalidate some tests that point to `view_item_by_slug`.  (If there had been any TBv1 tests, my commit b08e69d8 would have invalidated them, but we dodged that bullet...)

As always for such things, we want to remain as local as possible.  On the other hand, `view_item_by_slug` is clearly the right name for this path.  So I think the path is the following:

1. Remove the above line.  Change the name from `view_topic` to `view_item_by_slug`.
2. Check that tests still pass.
3. Audit the remaining code base for instances of `view_topic` and change them to `view_item_by_slug`.  The base template comes to mind, but we have to check _everywhere_ to be sure we don't 500 somewhere.

# Phase Two

After a couple days, when we're sure that we're happy with the TBv2 deployment, we should remove the code that we no longer need, such as `TopicBlogLegacyView`.

**Comment by Shriukan33** [comment]
Last traces I see from TBv1 are the models TopicBlogPageManager and TopicBlogPage. (along with their admin panel counterparts) 
Is it safe the delete ?

**Comment by JeffAbrahamson** [comment]
We can surely trim down the model (which will delete fields, but we should be careful deleting the model entirely.  There's some stuff written on this that I skimmed, just enough to realise it's complicated and we should come back  to it.

We can surely delete any functions that make reference to it.

Probably the manager is safe to delete, it doesn't create in-database structures I don't think.

It will require a bit of research and a bit of testing to see what makemigrations actually does (i.e., that we don't create weird situations that are hard to understand later).
