### ISSUE TITLE
Fix error message on slugfield

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#257]
Default message doesn't represent the current working state of the field (it mentions underscores for example). 
Besides it appears in English.

**Comment by Shriukan33** [comment]
Can't reproduce since introduction of Slugifier Ajax @JeffAbrahamson

**Comment by JeffAbrahamson** [comment]
ok, does that mean you want to close the issue?  Or do we keep it for something?

**Comment by Shriukan33** [comment]
Yes, the relevant issue is extend Slugifier to CTA slugs, which, by extent, solves this one as well.
