### ISSUE TITLE
Create a page for CF

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#294]
Create a page that explains the CF, and sort of mimics the behavior of the CF page with 7 buttons corresponding to donation amounts.

**Comment by JeffAbrahamson** [comment]
What view are you thinking?

**Comment by Shriukan33** [comment]
> What view are you thinking?

I was thinking making a new category of content "other" and a template crowdfunding.html which would be just for this purpose. Deletable once we're done with this page.

**Comment by JeffAbrahamson** [comment]
Might make sense to use `AssoView`?

**Comment by Shriukan33** [comment]
> Might make sense to use `AssoView`?

Wasn't very familiar with this View, indeed it seems to accomplish what we want. 

So I need to create a new URL in urls.py of assoview, passing the args directly in urls.py ? Like you did with nous contacter ? 
![image](https://user-images.githubusercontent.com/70256364/142885987-f63e933d-36c1-44ec-831d-b63826d15a9d.png)

**Comment by JeffAbrahamson** [comment]
In general, we don't delete...

**Comment by JeffAbrahamson** [comment]
Is this closable?

**Comment by JeffAbrahamson** [comment]
Is this closable?
