### ISSUE TITLE
TBv2 header slug isn't rendering

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#319]
it should offer click-through on the image header

**Comment by Shriukan33** [comment]
I don't think the image should be redirecting to another page, unless you specifically clicked a button to do so. 
In my opinion, having a button over the image to navigate is enough, having an implicit link under an image is, in my experience, an very uncommon design and could lead to confusion especially if the user attempted to do something else (Copy paste the title, or simple handling their phone so it clicks on the image from the borders of the screen). 

Do you have use cases where having the image clickable implicitly is desirable ?

**Comment by Shriukan33** [comment]
9 months later, I still don't think that the header should be clickable, reopen if you disagree
