### ISSUE TITLE
Fix Failing test on TBv2 ListView

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#352]
A test fails on TBIListView, lot has changed recently so better check for that. 
Here is the failing message : 
```

======================================================================
FAIL: test_full_list_display (topicblog.tests_staff_users.TBIListStatusCodeTests)
Test the status code of the TopicBlogItemList view
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/benja/Documents/GitHub/tn_web/transport_nantes/topicblog/tests_staff_users.py", line 500, in test_full_list_display
    self.assertEqual(len(response.context["object_list"]),
AssertionError: 2 != 3 : The list of items must be the same length as the number of items in the database.
number of items : 3
number of items in the list : 2

----------------------------------------------------------------------
```

**Comment by Shriukan33** [comment]
I've investigated the failing test, I think the fail comes from there :
https://github.com/transport-nantes/tn_web/blob/104707c5d10b2512b8e529f40fbde55c9876fcab/transport_nantes/topicblog/views.py#L311
introduced in commit 7cc3ce5
The queryset is filtering slugless items, this is the one not in the list that makes the test fail. Removing the .annotate() obviously breaks the display of information, but makes the test pass.
Now, because the TBILIstView does work for our practical use,  maybe I should set the expectations to be all items minus the number of slugless items ?
Don't know how to approach this, fixing the test to fit our build, or changing the build to meet the test ?
13 h 50
the get_queryset() function in the model BaseLIstView is basically a model.objects.all()
So at the beginning, qs does hold all items, even the slugless ones

**Comment by JeffAbrahamson** [comment]
Questions:  How do we want to treat empty slugs, should they show up in the list view at all?  I'm inclined to say that you can save a page with an empty slug, but you shouldn't expect to see it in a list of slugs.  It will be automatically cleaned up if like any draft after enough time has passed _(not yet implemented)_ or you just wanted to preview and you don't need list view.

If that sounds reasonable to you, too, then changing the test is the right thing to do.
