### ISSUE TITLE
Clean up:  what is the status of these branches?

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#359]
If these are active, let's finish them.
If these are not active, let's delete them.

* avoid-logic-in-js-210 / 2a59a72
* track-donation-button-origin-299 / b98874d

**Comment by Shriukan33** [comment]
#210 is closed, nothing to add on that. 

#299 on the other hand has a status update here

https://github.com/transport-nantes/tn_web/issues/299#issuecomment-999667351

Going to quote the status here: 

> I tested 3 cases on both the original Donation form and Fixed amount form : 1) Going to homepage of the site 2) Closing the tab and 3) Going to another domain Turns out, Tracking only happens if you close the tab. Leaving it by going to another URL (internal or not) doesn't allow the save. However the beforeunload event does fire (it's the one that POST info) ! It's simply blocked by firefox (img 1) that documents "NS_BINDING_ABORTED". A quick google search shows this [SO topic](https://stackoverflow.com/questions/704561/ns-binding-aborted-shown-in-firefox-with-httpfox) but this doesn't explain why it works when we close but not otherwise. I probably need to understand what's a NS binding. From what i've seen, without being sure, it looks like closing doesn't prevent requests but loading a new URL will interrupt the ones that were being made on the previous URL.
> 
> Adding future expire date in the Header doesn't solve this.

So basically i'm stuck by an error on Firefox, as explained above

**Comment by JeffAbrahamson** [comment]
ok, I've removed `avoid-logic-in-js-210`.

Usually github removes branches on PR, but there are a number of edge cases where it doesn't happen, and when you think through them, it's usually clear why github couldn't be 100% sure.  It's good to make a habit of making sure your branches get removed once you're done with them.

We'll leave #299 for another day then!
