### ISSUE TITLE
Clean up CSS

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#362]
Remove all classes that we aren't using.

**Comment by Shriukan33** [comment]
Do you have tools to get that ? The only solution I have would be to grep the class name in the project, but it's time consuming.

**Comment by Shriukan33** [comment]
I don't feel that our classes are an inconvenience at the time, especially since we stopped filling mobilitains.css with every style and moved to per-page css.
It's easier to maintain and tell if a given class is still used or not. 
last, this doesn't sound very urgent.

**Comment by JeffAbrahamson** [comment]
It's not urgent, but that's not a reason to close it.

Indeed, one of the issues with our site is that we make too many requests for css and js, which leads to cold cache hits and multiple requests per page.  There exist several solutions to this problem.

Not _ever_ cleaning up is not on the short list of solutions. ;-)

**Comment by Shriukan33** [comment]
I'm currently looking at this, and it's an issue that has been an itch for a while, I've found this lib : https://django-compressor.readthedocs.io/en/latest/

It solves the js cache problem and bundles + minify our files, two birds with one stone if you like. 
I'll make some research to compare existing libs and see what's fit for our needs.

**Comment by Shriukan33** [comment]
> I agree that something like that is in our future. The RTD page begins by saying "many solutions to this problem exist for django", which other ones have you found? Have you done some analysis or is this a "use the first one I saw" solution?
> 
> Remember that this is not urgent...

I've found solutions that mainly relied on webpacks, which needed a NPM install and some JS libararies. 
The installation was easy and solved the "cache isn't updated when I change my js file" problem without complications.

I think this is important when we want to push JS files like in Mobilito so the update is live right away.

**Comment by JeffAbrahamson** [comment]
SGTM.
