### ISSUE TITLE
Update helloasso text

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#37]
qui sommes-nous ?

Notre mission
C'est parfois difficile, les transports : Des bouchons, des tramways et
des bus trop peu fréquents, bondés ou encore des aménagements inadaptés
à la sécurité des piétons et des cyclistes.

À Transport Nantes, nous croyons que ces inconvénients, ces maux, loin
d'être des phénomènes indépendants, vont plutôt ensembles. Nos systèmes
de transports, ont depuis la deuxième guerre mondiale, ont été
construits pour la voiture individuelle.  Certes, nous avons fait
quelques progrès dans la dernière décennie mais le système penche encore
trop vers ce mode de transport.  Aucun système en déséquilibre ne peu
être satisfaisant pour ses usagers.

La voiture est essentielle, disons-le tout d'abord, dans de nombreux
territoires.  Toutefois, trop souvent elle est le seul choix possible,
même pour des déplacements de courte distance.  Ce qui mène à la
frustration de celles et ceux qui souhaitent s’en passer. Nous ne vous
dirons jamais comment vous devez vous déplacer.  C'est votre choix. 
Nous défendrons toujours votre choix.  Notre objectif, c'est tout
simplement de militer pour que vous en ayez un !
Certes, les transports en commun seront toujours moins commodes en
périphérie des agglomérations et les voitures moins adaptés au centre.
Pour autant une métropole dans laquelle la voiture est obligatoire en
périphérie, sans alternative, bannie en centre ville nous créerons de
plus en plus d’embouteillages.
Notre objectif est simple.  Pour tout déplacement
    • Si la distance vous semble raisonnable à pied, que vous soyez à
l'aise à pied.
    • Si la distance vous semble raisonnable à vélo, que vous soyez à
l'aise à vélo.
    • Si votre humeur tend vers les transport en commun, qu'il existe
une option raisonnable.
    • Si un véhicule à moteur vous convient le plus, que cela soit
possible également.
Et ceci, pour tout citoyen, quelque soit son âge, des plus jeunes aux
plus âgés, partout dans la métropole Nantaise.

Nous avons mis un demi-siècle pour construire un environnement qui
favorise la voiture à ce point.  Nous mettrons un demi-siècle encore
pour construire un environnement plus sain.  Nous proposons tout
simplement qu'on commence aujourd'hui, ensemble, à construire ce que
nous voudrions donner un jour à nos petits enfants.

Partie adhésion

Adhésion liberté

Bien que votre adhésion, voire vos dons, soient essentiels à notre
fonctionnement, votre voix se joignant aux nôtres est encore plus
importante. Si les adhésions proposées ne vous correspondent pas, vous
pouvez optez pour une adhésion personnalisé.

**Comment by YXWVECWUHKAVHWQJRGLHKLHRJDNPQH** [comment]
Probablement encore une coquille ici (à la toute fin) : adhésion personnalisé**e**
