### ISSUE TITLE
Confirm signup workflow

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#372]
- [x] create a templatetag using md on a TBv2 item
- [ ] walk through the workflow -- we want this not to need customisation in the sense of additional templates for each usage
- [ ] document which items are available via md, which aren't

**Comment by Shriukan33** [comment]
What does the templatetag display ? Does it look like the "Restez en contact" button on the main page ? 

I don't understand what's the goal of this issue

**Comment by JeffAbrahamson** [comment]
So instead of saying `{{ content | markdown }}` we'll say `{% markdown content %}`.  The advantage is that we can pull in the context, which means we can display forms.  Because without the context, we can't get the CSRF token.

**Comment by Shriukan33** [comment]
in your example content is what ? 
I've trouble making the bridge between "confirm signup" (which is the "restez en contact" button, right ?) and the markdown filter on a field

**Comment by JeffAbrahamson** [comment]
"content" is whatever you are running through the markdown filter.  Here's an example from `topicblog/templates/topicblog/content.html`:

> {{ page.body_text_1_md|markdown }} 

If you want to say something like `[[mlp:quick-signup]]((sign-me!))` (or whatever the markdown is/would be), you need for that markdown to render with a context object,  because you're emitting a form, and the form needs a CSRF token.
