### ISSUE TITLE
Pre-populate email if logged in

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#383]
If the user is authenticated (and so we know her/his email address), don't even ask for the email address in MLP forms, nor the captcha.  Just do signup directly.

**Comment by Shriukan33** [comment]
Issue #391 is the first step to make it work

**Comment by jyoost** [comment]
@Shriukan33. Are you going to do anything with the django_cms integration?

**Comment by Shriukan33** [comment]
One-click subscriptions are implemented now, closing
