### ISSUE TITLE
Make inclusion-tag context-sensitive

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#391]
The Mailing List markdown tag renders HTML code that isn't context-sensitive. 

The render_inclusion_tag_to_html() function, called whenever we use the `[[news:arg]]((text))` markdown templatetag, creates a new context space in the html it creates. 
https://github.com/transport-nantes/tn_web/blob/f838bb0c8da753431cbdec9cf915c4632aec3ad8/transport_nantes/topicblog/tn_links.py#L63

It means that the HTML that is produced by this tag can't access the context variables contained in the context dictionary returned by the view. it prevents this part of the code to access variables such as `user`, and its attributes `user.is_authenticated`

Example of this in a TBItem where in body_1_markdown I entered the  `[[news:arg]]((text))` markdown templatetag with index as a slug. 
This page is particular because : 
*  it has the `{% show_mailing_list mailinglist="arg" %}` tag in its html (see this line : https://github.com/transport-nantes/tn_web/blob/b7829054e5f7c48ca178a5b8be27e2e270b599d2/transport_nantes/topicblog/templates/topicblog/content.html#L123) 
* It also has the markdown templatetag. 

The result is this : 
![image](https://user-images.githubusercontent.com/70256364/148972278-bad1c819-ad60-4a5b-9aec-7db50c1bde33.png)
![image](https://user-images.githubusercontent.com/70256364/148972446-3be0a5f5-6a53-4d68-b689-17e0ce737658.png)

To display the `this_context` var, I added it to the render_inclusion_tag_to_html() function as this : 
```py
def render_inclusion_tag_to_html(tag_source, tag_name, kwargs):
    """Render an inclusion tag to a string.
    """

    template_string = f"{{% load {tag_source} %}}{{% {tag_name} %}}"
    template_context = {'csrf_token':  settings.csrf_token,
                        'mailinglist': kwargs['mailinglist'],
                        'this_context': "render_inclusion_tag_to_html"}  # <-- HERE
    html = Template(template_string).render(Context(template_context))
    return html
```

And in the `transport_nantes/mailing_list/templates/mailing_list/panel/mailing_list.html`, template responsible for displaying both the markdown templatetag and the `{% show_mailing_list mailinglist="arg" %}` tag, I inserted this : 
```html
	{% if request.user.is_authenticated %}
		<h1>User is auth : {{ user.email }} </h1>
		<h1> This context var : {{ this_context}} </h1>
	{% else %}
		<h1> user not auth </h1>
		<h1> This context var : {{ this_context}} </h1>
	{% endif %}
```

This shows two things : 
* At rendering time, `{% show_mailing_list mailinglist="arg" %}` tag doesn't have access to `this_context` but `[[news:arg]]((text))` does. 
* Still at rendering time, `[[news:arg]]((text))` does not have access to `request.user` context variable, but `{% show_mailing_list mailinglist="arg" %}` tag does.

To solve this issue we'd need to make `[[news:arg]]((text))`  MD tag aware of the context of the page, at least the request. 

This issue is a pre-requisite of #383

**Comment by JeffAbrahamson** [comment]
Oh, cool, I'd not thought of that.  But it makes sense.
I wrote TNLinkParser at a time when markdown was a filter and had no context.  When I changed markdown to tn_markdown and so provided it with context, I never told TNLinkParser.

I think the fix is to pass the context to TNLinkParser (in tn_markdown(), but maybe there are other places) and then when it calls render_inclusion_tag_to_html() it adds self.context as a first arg.  Then render_inclusion_tag_to_html() doesn't make a new context but uses the one it's got.

Good job debugging it!
