### ISSUE TITLE
Redesign observatoire de la grande mobilité as per Simon suggestions

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#40]
So here's how I see it. Ok, the drawing attached is crap due to my cellphone camera but you'll get the idea.

3 screens. Number 1 on the left:

* Logo, "observatoire", hamburger menu, all on the same stripe.
* then, underneath, a map.
* and a button that says 'localisez moi" and another one that says "commencer l'enregistrement" or something like that.

When you click on that last button, you'll get to screen 2:

* same menu on top.
* a button that says "arreter l'enregistrement" with a "stop" or "pause" icon
* 4 buttons at the bottom of the screen using the whole bottom half, with 4 icons that you can find on noun project or somewhere else (a font maybe) showing a bike, a pedestrian, a car and a train. Of 4 different colors. Such as a windows logo

When you press "arreter l'enregistrement" you'll get to the 3rd screen

*    same menu
*    the same is a recap with a map of where you are
*    the a line that says "le 19/05/20 de: 13h05 à: 13h24"
*    then the numbers for each transport mode
*    then a buttons that says send

A forth screen, that I haven't drawn, which says thank you and allows you to share the thing on FB, Twitter, etc.

There is also a screen zero, where you explain shortly what it is and what's going to happen.

Why all this? The user needs a lot of feedback. A user needs to know what's going on - is it started or not, since when, etc - and needs a reward at the end: a result screen (so that he/she can see the work that's done) and and a way to share it.

I don't think you need to be able to correct the numbers if you press the buttons wrong. This is going to be very minor occurance, I think. Maybe you can make the screen 3 editable though.

About screen 2: the user needs to be able to press the buttons without looking, so they have to occupy the whole bottom screen and there needs to be nothing else there. If you can add a little sound with each press that's even better. also if you can show the current duration of the recording on top of the "stop" button that's top.

I would have done that for you in no time had you keep the Divi/WP combo. But it's bootstrap so you'll have to do it yourself.

Anyway think of your users as mentally challenged people who understand very little of the job they have to accomplish. We're all like this when we're not really in charge, not paying attention, and not paid in the end. Make everything super simple and clear. As little words as possible.

Also imho not sure you can ignore someone in a small street staying there for 15 minutes and seing one car. If you don't record any start/end time, you'll lose that session and I'd say it's relevant - as in "no bike seen in this street despite being the shortest route between 2 major points". 

![ux_path](https://user-images.githubusercontent.com/1220683/82736593-3feef180-9d2b-11ea-95cb-c5ced56abb97.jpg)

**Comment by Shriukan33** [comment]
![image](https://user-images.githubusercontent.com/70256364/175047320-84f5d5c6-c4d7-4ae6-b1f1-233d4d06bc43.png)
![image](https://user-images.githubusercontent.com/70256364/175047345-316d2fc3-cbcf-4f9a-9769-3265e5494b3f.png)
![image](https://user-images.githubusercontent.com/70256364/175047376-37774a7f-38c0-4c19-9922-e4806068491c.png)
