### ISSUE TITLE
slug fields limitations

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#413]
* slug fields are limited to 50 characters

Is this necessary?  If it is, we should document it in the model.  If it's not, we should remove the constraint.

* pasting non-ascii doesn't do the right thing

For example, pasting "mobilité" gives "mobilit".

**Comment by JeffAbrahamson** [comment]
For the length, the [default is 50](https://docs.djangoproject.com/en/4.0/ref/models/fields/#slugfield).  Once this morning's PRs are merged, I'll add a `max_length=90`.  Probably 80 is enough, but 90 gives extra space.  (Too long makes for weird copy/paste.)

**Comment by Shriukan33** [comment]
This is solved, we sanitized slug inputs in 5792be7dd03f72e9c8936cf3f9bc28a65c8c9cb3 , closing
