### ISSUE TITLE
make slugs modifiable

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#421]
If the user modifies the slug of an article, this should make a new copy, just like any other save.  Ideally, of course, we should warn that this is happening (change "sauvegarder" to "creer").

**Comment by Shriukan33** [comment]
We do have an event listener that tells us we are modifying, and we can save it as a new object, should we change the button's text as well or are we good ?

**Comment by JeffAbrahamson** [comment]
I think we're good!
