### ISSUE TITLE
Add TBItem tests

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#436]
* Confirm sort order in list view.
* Confirm that edit + save result in new item and that old item is unmodified.
* Confirm that edit sets `user` field to the person who edited.
* Confirm that creating three items (A, B, C) with the same slug, publishing B, then C, then B sets all three dates as expected.
* Confirm that creation (modified) date is always less than published date.
* Confirm that `first_published_date` is never greater than published date.
* Confirm that the page marked as being active in list view is the same page as the view-one function will select

**Comment by Shriukan33** [comment]
The added coverage @mcmikashi did is enough for this issue, I think :slightly_smiling_face:
