### ISSUE TITLE
Update our publicaction tracking model for all TBObjects

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#543]
We unintentionally created a bit of a mess.  When we publish an object, we unpublish all others with the same slug.  This is reasonable.  But `first_publication_date` tracks when _this particular slug_ was first published.  As a result, we have no trace of which versions of a slug were previously published.  And this makes clean-up hard, because we can be relatively aggressive in cleaning up "old" things that have never been published, but things that were once live we might want to keep longer.

Now, admittedly, we have the `publisher` field, and this at least tells us that the object was once live.  But it doesn't tell us when.

Consider that some objects already have dozens of versions.  Fast forward a couple years.  This will be a mess.

A proposal is that we add a field `unpublish_date` that tells when this particular object stopped being live.  Then in `TopicBlogBaseViewOne.post()` we add one extra update command:

```
    self.model.objects.filter(
        id=tb_object.id).update(unpublish_date=datetime.datetime.now())

```

Then in the dashboard we drop the word about _retiré_ and instead say "unpublished on ..." (dépublié ?).

**Comment by JeffAbrahamson** [comment]
Can template_name be a dropdown of available templates like for TBItem?

**Comment by Shriukan33** [comment]
All items that have a first_publication_date have been once published, those who don't never have. We could clean up those who don't have one, as it's never reset, the code goes like this : 
```python
self.model.objects.filter(
                    slug=tb_object.slug).exclude(
                        id=tb_object.id).update(publication_date=None)
                tb_object.save()
```
Only publication_date is reset. So I think it would be safe to delete those who don't have a 1st publication date, but the risk is that older pages might not have one, as I'm not sure about when we introduced that field.

To solve that, we could delete those who don't have a first_publication_date and have a created_at > [date we introduced that field] 

What do you think ?

**Comment by JeffAbrahamson** [comment]
Quick taxonomy:
*  **Page is active**
   * `publication_date` is non-null
   * `publisher` is non-null
* **Page was active**
   * `publication_date` is null
   * `publisher` is non-null
* **Page has never been active**
   * `publication_date` is null
   * `publisher` is null

So, except for quite old articles, we can already tell the difference.

I think the main point is that it would be helpful to know how long it's been since something was unpublished.

New taxonomy:
*  **Page is active**
   * `publication_date` is non-null
   * `publisher` is non-null
   * `unpublish_date` is null
* **Page was active**
   * `publication_date` is null
   * `publisher` is non-null
   * `unpublish_date` is non-null
* **Page has never been active**
   * `publication_date` is null
   * `publisher` is null
   * `unpublish_date` is null
