### ISSUE TITLE
Add teaser_words field to TBLauncher

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#582]
Add an int field to `TBLauncher` called `teaser_words` that defaults to 50.

The `item_teaser` templatetag should use this int rather than always using 50.  This will let us fiddle with it when that seems the right thing to do, say the cutoff changes meaning subtly.

**Comment by mcmikashi** [comment]
The` item_teaser` uses a TBItem object if we want to use teaser_words we should add this to TBItem or add a new argument to the item_teaser templatetags function teaser_words that lets us control the number of truncwords ?

**Comment by JeffAbrahamson** [comment]
Aha, I missed this in the code review.  The teaser should use the TBLauncher and access the TBItem from there.  So this is a bug in the teaser template.

Recall that the eventual logic is that some function will provide an ordered list of (probably) six TBLauncher slugs, and the dynamic index page will render them as a teaser, four standard launchers, and a second teaser.

**Comment by JeffAbrahamson** [comment]
LGTM.
