### ISSUE TITLE
Clear the admin banner for TBL

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#602]
![image](https://user-images.githubusercontent.com/70256364/160867001-7e931eef-0489-4943-81bc-39262545afe5.png)

The banner says (brouillon) while there is no "published" state for TBLaunchers. 
To clear this confusion I suggest we delete the "(brouillon)" for those.

**Comment by JeffAbrahamson** [comment]
Yup, I think the only thing we want to say is "actuellement actif" or something.  (Maybe we should globabaly drop the word published (except for the button, "publier") and just say "actuellement actif", "actif entre dd mmm yyyy et dd mmm yyyy", and "jamais actif".  These would be in relatively small text in most places, they are just informational to help orient people.

**Comment by JeffAbrahamson** [comment]
This apparently appeared between when master was last deployed and when beta was.

In addition, in dev, it's fine...

I don't believe the problem is the beta or admin banner.  It's assuredly CSS.

**Comment by Shriukan33** [comment]
> This apparently appeared between when master was last deployed and when beta was.
> 
> In addition, in dev, it's fine...
> 
> I don't believe the problem is the beta or admin banner. It's assuredly CSS.

My dev version (at 594534d / master) has the banner issue, maybe you didn't clear the cache ?

**Comment by JeffAbrahamson** [comment]
In dev, you don't talk through cloudflare.  I did force reload of css -- dev servers said 200 and not 304.  (Just noticed it colours differently based on status code!)

Strange.
