### ISSUE TITLE
Reword the login email

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#604]
The one I received said : 

>Bonjour, Si toutefois vous n'avez pas demandé la création d'un compte, vous pouvez simplement supprimer ce mél. https://beta.mobilitains.fr/auth/activate/<token>

A paragraph seems to be missing. 
Also the link is not clickable, copy/paste seem to be the only solution.

**Comment by JeffAbrahamson** [comment]
In addition, we don't have an (external) idea of account, so the language is just wrong.

Probably best just to say something like "if you weren't expecting this mail, you can delete it".

**Comment by Shriukan33** [comment]
this issues now extends to improve globally the mail sent to connect to our website.
