### ISSUE TITLE
user_subscribe_count doesn't return a correct number

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#623]
From beta : 
![image](https://user-images.githubusercontent.com/70256364/161563559-7d037447-6223-45eb-ac1c-147e30f94302.png)
![image](https://user-images.githubusercontent.com/70256364/161563575-0829e4a3-97b1-45f4-80a6-1c7045b60bac.png)

The number of recipients should have been 1, and yet it still displays 2. 
Because the send records show only 1 email sent and it's been confirmed by Jeff that he hasn't received an email, it seems that the fault falls on the user_subscribe_count function 

https://github.com/transport-nantes/tn_web/blob/08dd391ed996cece45b9e67d42837427426065bd/transport_nantes/mailing_list/events.py#L51

We should fix it or use another function and deprecate this one to get a proper display. 

Edit : 
Update this test : 
https://github.com/transport-nantes/tn_web/blob/b183fb8952ff1bb2f83a4905998ee53909dd5546/transport_nantes/mailing_list/test_events.py#L52
To have unsub event inside it.

**Comment by JeffAbrahamson** [comment]
That function is tested, no?  So we should figure out why it doesn't work, why the test doesn't pick that up, and fix it, not introduce a new function.

**Comment by Shriukan33** [comment]
> That function is tested, no? So we should figure out why it doesn't work, why the test doesn't pick that up, and fix it, not introduce a new function.

Wasn't thinking about creating another function, just using one we already have : 
https://github.com/transport-nantes/tn_web/blob/08dd391ed996cece45b9e67d42837427426065bd/transport_nantes/mailing_list/events.py#L86

We check the length of to get the number of recipients, but sure, we should see what's going on with this function. 

And yes there is a test, but it doesn't test the case where one unsubscribes. 
https://github.com/transport-nantes/tn_web/blob/b183fb8952ff1bb2f83a4905998ee53909dd5546/transport_nantes/mailing_list/test_events.py#L52

**Comment by JeffAbrahamson** [comment]
Ah, the function next to it has unsub tested.  That's already a bug. ;-)

The function finds the latest sub or unsub for each user, makes a list of that, then counts the number for which the latest is a sub.  I suspect it's enough to look at the intermediate values to see what's happening.  And to make another test where someone unsubs.

**Comment by mcmikashi** [comment]
close via  7e89ceff1872af82f699092e4fecfeacbc9dccff
