### ISSUE TITLE
Create different types of Mailing Lists

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#643]
The idea behind the different types is a different handling of the unsubscription process, so far we see 3 types of mailing lists : 
* Petitions, from which you can't unsubscribe (you don't unsign a petition)
* Normal mailing list (newsletters), to which we have a unsub flow already running
* Press mailing list, specifically for journalists.

The later will have in their emails instead of "se désinscrire", "Préférences presse". 
Upon click, they are going to be shown a list of mailing lists with checkboxes : If you are subscribed the checkbox is checked, and vice versa.
At the bottom, a save preferences button.
 
<hr>
Current problems : 

* The TBEmailSendRecord is the only  model used for now, we might want to add a flag to tell it's a press or the lookup by ID will look for TBESendRecords instead of TBPSendRecords.
For now independently of if the sent object is a TBPress or TBEmail, a TBESendRecord is created.

**Comment by Shriukan33** [comment]
Current problems : 
* The checkboxes are either all checked or none is : It depends if the first item in the queryset returns `True` when asked if the user is subbed.

The TBEmailSendRecord is the only  model used for now, we might want to add a flag to tell it's a press or the lookup by ID will look for TBESendRecords instead of TBPSendRecords.
For now independently of if the sent object is a TBPress or TBEmail, a TBESendRecord is created.

**Comment by JeffAbrahamson** [comment]
> The TBEmailSendRecord is the only model used for now, we might want to add a flag to tell it's a press or the lookup by ID will look for TBESendRecords instead of TBPSendRecords.

I don't think you want to invalidate referential integrity by adding flags like this.

Woudl it make sense simply to do empty inheritance TBEmailSendRecord -- make TBSendRecordBase, then inherit from it to make TBEmailSendRecord and TBPressSendRecord?

We can talk about it on the call.

**Comment by Shriukan33** [comment]
Fixed the bug in https://github.com/transport-nantes/tn_web/commit/18846fea6f64e346aae9e6784098657293ecfa54

**Comment by JeffAbrahamson** [comment]
I'm looking at this more closely and I'm completely lost in your comments and questions.

On the model `MailingList` there is currently a boolean, `is_petition`.  I'm proposing we replace it with an enum: newsletter, petition, press.  I think that is all this is.

What additional complexity is there at this point?

**Comment by JeffAbrahamson** [comment]
This, plus the TB work, _might_ mean we retire the `Petition` model.

**Comment by Shriukan33** [comment]
> I'm looking at this more closely and I'm completely lost in your comments and questions.
> 
> On the model `MailingList` there is currently a boolean, `is_petition`. I'm proposing we replace it with an enum: newsletter, petition, press. I think that is all this is.

Yes, this is what I did in 70ecff66793ab7e844d2659bf08946a69cc0a360, I added the enum as you mentioned. I didn't retire the is_petition just yet because I figured that would come in another PR where I retire properly the whole Petition thing

> What additional complexity is there at this point?

I did a bit more than adding the new type, I also added the press unsubscription management that comes with the new type of mailing list : ("PR", "Press")

Maybe I shouldn't have flagged this issue in those commits, it's related in the sense where I add the new mailing list type, and the logic that comes with it in regard of unsubscriptions 

i'll make an issue to retire the Petition model

**Comment by JeffAbrahamson** [comment]
> I did a bit more than adding the new type, I also added the press unsubscription management that comes with the new type of mailing list : ("PR", "Press")
> 
> Maybe I shouldn't have flagged this issue in those commits, it's related in the sense where I add the new mailing list type, and the logic that comes with it in regard of unsubscriptions

Indeed, a second issue and a clearer explanation might just sort that!
