### ISSUE TITLE
/presse/ 500's

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#655]
I suspect this is only because we have zero entries, but we could still display something better than a 500.

https://beta.mobilitains.fr/presse/

**Comment by JeffAbrahamson** [comment]
Actually, it's not empty now, so it wasn't that.

It's the missing og_image file.

**Comment by mcmikashi** [comment]
yes the first pressmention doesn’t have og fields. it' was created before the implementation of og field I think.

**Comment by mcmikashi** [comment]
I made the update it's work now but look bad.
