### ISSUE TITLE
Benja learning task

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#715]
Understand the difference between an email body, email headers, and the email envelope.

This is not a long task, please close to acknowledge that the vocabulary makes sense, that you understand enough about SMTP not to get confused on what's in the header and what's in the envelope.

**Comment by Shriukan33** [comment]
I've been reading these : 
https://www.mybluelinux.com/what-is-email-envelope-and-email-header/
https://www.mybluelinux.com/explanation-spf-sender-policy-framework-in-all-details/
https://www.mybluelinux.com/explanation-dkim-domainkeys-identified-mail-in-all-details/

I believe it's clearer now.
