### ISSUE TITLE
launcher preview still filters to published

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#732]
In `topicblog/templatetags/launcher.py` the queries all contain `publication_date__isnull=False`.  This causes preview (i.e., ViewOne) to fail because a new item in general is not currently published.  And if we wish to look back at previous items, we get the currently published item, not the item we requested.

This clearly needs a failing test (i.e., a test that reproduces the two cases above and fails, but that does not fail once the issue is resolved).

This is urgent in the sense that it is short but affects our ability to manipulate launchers easily and transparently.

**Comment by JeffAbrahamson** [comment]
I think the way to start this is to modify the queries in `topicblog/templatetags/launcher.py` to look something like this:

```
@register.inclusion_tag('topicblog/template_tags/launcher.html')
def launcher(slug, pk_id=None):
    query = TopicBlogLauncher.objects.filter(
        slug__iexact=slug, publication_date__isnull=False).first()
    if pk_id is None:
        launcher = query.filter(
            publication_date__isnull=False).order_by(
                '-publication_date').first()
    else:
        launcher = query.filter(id=pk_id).first()
    if launcher is None:
        logger.error(f"launcher failed to find slug: \"{slug}\".")
    return {'launcher': launcher}


@register.inclusion_tag('topicblog/template_tags/item_teaser.html')
def item_teaser(slug, pk_id=None):
    query = TopicBlogLauncher.objects.filter(
        slug__iexact=slug).first()
    if pk_id is None:
        launcher = query.filter(
            publication_date__isnull=False).order_by(
                '-publication_date').first()
    else:
        launcher = query.filter(id=pk_id).first()
    if launcher is None:
        logger.error(f"item_teaser failed to find launcher slug: \"{slug}\".")
        item = None
    else:
        item = TopicBlogItem.objects.filter(
            slug__iexact=launcher.article_slug, publication_date__isnull=False).first()
        if item is None:
            logger.error(f"item_teaser failed to find slug: \"{slug}\".")
    return {'launcher': launcher, 'item': item}

```

Then we just need to make sure we pass the pk_id when we're editing/previewing but not when we're showing the published version.

Note that I'm incorporating first steps of #722 by introducing the sort condition.

**Comment by Shriukan33** [comment]
https://github.com/transport-nantes/tn_web/pull/718 I did open a PR about this @mcmikashi , just not updated yet because it needed clarifications

**Comment by JeffAbrahamson** [comment]
> #718 I did open a PR about this @mcmikashi , just not updated yet because it needed clarifications

![image](https://user-images.githubusercontent.com/1220683/168538544-dedfb5aa-3f54-41bb-83e0-9872ef308561.png)

Of course, the only code that counts is code that runs. ;-)
