### ISSUE TITLE
Add try_count field to SendRecord

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#737]
We need to know when to stop trying, and one is not the right answer.

I think we can use celery to auto-schedule, so that we can do exponential backoff up to some fixed attempt limit (or passage of time), at which point we fail.

**Comment by Shriukan33** [comment]
From AWS docs : https://docs.aws.amazon.com/ses/latest/dg/send-email-concepts-process.html
>Soft bounce—The ISP cannot deliver the email to the recipient because of a temporary condition, such as the ISP is too busy to handle the request or the recipient's mailbox is full. A soft bounce can also occur if the domain does not exist. The ISP sends a soft bounce notification back to Amazon SES, or, in the case of a nonexistent domain, Amazon SES cannot find an email server for the domain. In either case, Amazon SES retries the email for an extended period of time. If Amazon SES cannot deliver the email in that time period, it sends you a bounce notification through email or through Amazon SNS. If Amazon SES can deliver the email to the recipient during a retry, the delivery is successful. A soft bounce is shown in the following figure. In this case, Amazon SES retries sending the email, and the ISP is eventually able to deliver it to the recipient.

It seems that AWS retries on its own when appropriate

**Comment by JeffAbrahamson** [comment]
> It seems that AWS retries on its own when appropriate

Yes, that's part of the SMTP spec...

**Comment by Shriukan33** [comment]
So the issue is solved ? Or am I missing something ?
