### ISSUE TITLE
Donation should add to year list

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#753]
On making a donation, we should add the user to a list of this year's donors.

```
list_name = f"soutien_{ this_year }"
try:
    subscribe_to_list(user, list_name)
except (whatever the specific db not found exception is):
    create_list(list_name)
    subscribe_to_list(user, list_name)
```

Alternatively, perhaps `subscribe_to_list()` should have a boolean flag, defaulting to `False`, that creates the list if it doesn't exist (and logs that fact).

**Comment by Shriukan33** [comment]
Done in https://github.com/transport-nantes/tn_web/commit/3f8c968a7636f2ff824eb07e9c32d6d7d700817c
