### ISSUE TITLE
TBPress base template is missing contact info

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#764]
A contact email and phone number should be available in the model.  If absent, the email should default to press@ whilst the phone number should be absent (i.e., no default value).

**Comment by Shriukan33** [comment]
Hey I don't feel this is especially high, given that the contact info doesn't change very often or at all, the default might be enough. Want me to add a "phone_number" and a "mail_contact" field to TBPress ?

**Comment by JeffAbrahamson** [comment]
Didn't we already implement this with the contact field?

**Comment by Shriukan33** [comment]
Haha, right ! Guess we can close this now
