### ISSUE TITLE
Rebase on password_reset

### ISSUE THREAD

**Issue by Qlexio** [transport-nantes/tn_web#81]
@JeffAbrahamson 
you should watch my first attempt to do a rebase.
I know that there is no test but I just want to know if I used the git command well.

**Comment by Qlexio** [comment]
I forgot to tell you that I put my rebase in the branch called new_password_reset

**Comment by JeffAbrahamson** [comment]
I see this:

```
╭╴ (master %=)╶╮
╰ jeff@starshine:tn_web $ git checkout origin/new_password_reset 
Note: switching to 'origin/new_password_reset'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at dea9c3d Add password reset
╭╴ ((dea9c3d...) %)╶╮
╰ jeff@starshine:tn_web $ git-log-table -3
dea9c3d|2020-12-15|Alexandre BENARD| (HEAD, origin/new_password_reset) Add password reset
b35d46c|2020-12-11|Alexandre BENARD| Add password reset form
45f626d|2020-12-16|Jeff Abrahamson| (origin/master, master) Add template for developer settings_local
╭╴ ((dea9c3d...) %)╶╮
╰ jeff@starshine:tn_web $ 
```

**Comment by JeffAbrahamson** [comment]
So I see two commits added.

**Comment by JeffAbrahamson** [comment]
First commit tests clean:

```
╭╴ ((b35d46c...) %) [virt]╶╮
╰ jeff@starshine:transport_nantes $ python manage.py test --settings=transport_nantes.settings_tn
System check identified no issues (0 silenced).

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
╭╴ ((b35d46c...) %) [virt]╶╮
╰ jeff@starshine:transport_nantes $ 

```

**Comment by JeffAbrahamson** [comment]
Second commit tests clean:

```
╭╴ ((b35d46c...) %) [virt]╶╮
╰ jeff@starshine:transport_nantes $ git checkout origin/new_password_reset 
Previous HEAD position was b35d46c Add password reset form
HEAD is now at dea9c3d Add password reset
╭╴ ((dea9c3d...) %) [virt]╶╮
╰ jeff@starshine:transport_nantes $ python manage.py test --settings=transport_nantes.settings_tn
System check identified no issues (0 silenced).

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
╭╴ ((dea9c3d...) %) [virt]╶╮
╰ jeff@starshine:transport_nantes $ 
```

**Comment by JeffAbrahamson** [comment]
You change `settings.py` in order to make your tests run.  This is a hack and it's wrong.  If you need to change something like that for your dev work, change it temporarily (or permanently) in your `settings_localy.py`.  If you need to change it in your unit tests, change it in the unit tests.

**Comment by JeffAbrahamson** [comment]
Why do you need to change `transport_nantes/urls.py` and add paths at the root level?  You've already found that the auth code uses `reverse_lazy()`, so the names of the functions should surely be enough.  Why does the `reverse_lazy` not suffice for the auth code to find your paths when they're in the `authentication` package?

**Comment by JeffAbrahamson** [comment]
In the second commit you undo some of these things.  So maybe you've planned to do a second rebase to edit the commits.  (I forget that you asked me to look just at rebasing.  Sorry. ;-)

**Comment by JeffAbrahamson** [comment]
So just on the subject of "did I rebase well", looks good, I see two commits on top of `origin/master`.

**Comment by Qlexio** [comment]
@JeffAbrahamson 
I added tests to `origin/new_password_reset` then commited.
I did a rebase and squash the two last commits.
So there should still be 2 commits instead of 3.
Just tell me if everything is done well and I'll do a PR.

After I'll do the same on `origin/login_by_mail` but I've a question for this one.
There will be differences between the 2 branches, especially part of code well wroten in `new_password_reset` but not in `login_by_mail`. 
So, how will GIT manage that?
Do I have to do something special?

**Comment by JeffAbrahamson** [comment]
Good, I see a force update, so you did something right. ;-)
```
╭╴ (master *$%=)╶╮
╰ jeff@birdsong:tn_web $ git fetch
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 7 (delta 5), reused 5 (delta 5), pack-reused 2
Unpacking objects: 100% (7/7), 1.51 KiB | 257.00 KiB/s, done.
From github.com:transport-nantes/tn_web
 + dea9c3d...260ad5e new_password_reset -> origin/new_password_reset  (forced update)
╭╴ (master *$%=)╶╮
╰ jeff@birdsong:tn_web $ 
```

**Comment by JeffAbrahamson** [comment]
There are a couple items that are bothersome:
* `settings.py` is still modified.
* `transport_nantes/urls.py` is modified and unmodified
* some files have lines ending with spaces (relatively minor compared to the above two)

Tests pass, which is good.

**Comment by JeffAbrahamson** [comment]
For the differences between the branches, you'll want to rebase the new branch off of master (or off of the accepted PR, if necessary).  Sometimes this creates conflicts.  Git will notify you and ask you to fix those conflicts during rebase.

**Comment by Qlexio** [comment]
I see. Rebase had no conflict but I wonder what is going to happen at the PR.
For now, you can check `origin/login_by_mail` then I'll do a PR and we'll see.

**Comment by JeffAbrahamson** [comment]
There are still lines with whitespace at the end:

```
╭╴ ((66a6871...) $%) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ git diff 2b7cd73..66a6871 authentication/views.py | grep -E '\s+$'
+            
+            
 
 
 
 
╭╴ ((66a6871...) $%) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ 
```

**Comment by JeffAbrahamson** [comment]
There's a curious log comment about `settings.py` without `settings.py` actually having been modified:

```
╭╴ ((66a6871...) $%) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ git log 2b7cd73..66a6871 --stat | grep settings
    * Remove unused SESSION_COOKIE_AGE constant in settings.py
╭╴ ((66a6871...) $%) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ 
```

**Comment by JeffAbrahamson** [comment]
Tests aren't clean at HEAD (1 failure, lots of noise):

```
╴ ((66a6871...) $%) [virt]╶╮
╰ jeff@birdsong:transport_nantes $ python manage.py test --settings=transport_nantes.settings_tn 2>&1
Creating test database for alias 'default'...
......F.............
======================================================================
FAIL: test_mail_with_used_token (authentication.tests.TokenMailTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jeff/src/jma/transport-nantes/tn_web/transport_nantes/authentication/tests.py", line 503, in test_mail_with_used_token
    self.assertNotEqual(response2.url, "/")
AssertionError: '/' == '/'

----------------------------------------------------------------------
Ran 20 tests in 4.318s

FAILED (failures=1)
Destroying test database for alias 'default'...
System check identified no issues (0 silenced).
ObjectDoesNotExist
ObjectDoesNotExist
ObjectDoesNotExist
Mode dev : mél qui aurait été envoyé :

Bonjour,

Vous avez demandé la création d'un compte à localhost:8000.
Le lien suivant confirmera sa création.
Si toutefois vous n'avez pas demandé la création d'un compte, vous
pouvez simplement supprimer ce mél. 

http://localhost:8000/auth/activate/False/heuJ_wmUnD05hMKDCn3ChWIs17o%7C1%7Cqlhk5i%7C37ea0e7bc4095fc9a9e9


ObjectDoesNotExist
Mode dev : mél qui aurait été envoyé :

Bonjour,

Vous avez demandé la création d'un compte à localhost:8000.
Le lien suivant confirmera sa création.
Si toutefois vous n'avez pas demandé la création d'un compte, vous
pouvez simplement supprimer ce mél. 

http://localhost:8000/auth/activate/False/xdvGQPMavxM-lG8v5ozn6qow6d0%7C1%7Cqlhk5i%7C1f1595cd47cf49b7519a


ObjectDoesNotExist
Mode dev : mél qui aurait été envoyé :

Bonjour,

Vous avez demandé la création d'un compte à localhost:8000.
Le lien suivant confirmera sa création.
Si toutefois vous n'avez pas demandé la création d'un compte, vous
pouvez simplement supprimer ce mél. 

http://localhost:8000/auth/activate/False/JUJsRqAQzT138EeHrqrj_K4uOZU%7C2%7Cqlhk5i%7C35675d059e4511205e21


ObjectDoesNotExist
Mode dev : mél qui aurait été envoyé :

Bonjour,

Vous avez demandé la création d'un compte à localhost:8000.
Le lien suivant confirmera sa création.
Si toutefois vous n'avez pas demandé la création d'un compte, vous
pouvez simplement supprimer ce mél. 

http://localhost:8000/auth/activate/False/Ap1oPHkXHGFOCkfnAujA1_f0gFk%7C2%7Cqlhk5i%7C10addafb5d962cf5e7a8


ObjectDoesNotExist
ObjectDoesNotExist
ObjectDoesNotExist
Mode dev : mél qui aurait été envoyé :

Bonjour,

Vous avez demandé de connecter à votre compte à localhost:8000.
Le lien suivant vous le permettra.
Si toutefois ce mél ne correspond pas à votre demande, vous
pouvez simplement supprimer ce mél.

http://localhost:8000/auth/activate/False/LuK3mpfUGgvCp3y6BA-JVIe1VgM%7C1%7Cqlhk5i%7Ca8566404adca24a0a837


ObjectDoesNotExist
ObjectDoesNotExist
ObjectDoesNotExist

╴ ((66a6871...) $%) [virt]╶╮
╰ jeff@birdsong:transport_nantes $

**Comment by JeffAbrahamson** [comment]
I gave you a suggestion, with code, about how to set settings.role to test in a test.  The proposal was that it avoided printing so much noise to the log.  Why aren't you doing that?

Your tests are so noisy that it's easy to see that they don't pass.  (You didn't see that your own tests didn't pass before asking me to review.)

Be more careful please.  Take your time.  Writing software is detail-oriented.  The machine will do exactly what you tell it to do, no more, no less.  That takes a tremendous amount of concentration to get right.

**Comment by Qlexio** [comment]
1. I only have one blank line at the end of authentication/views.py which is the good way to code in python.
2. Test log is noisy because of the code you wrote because you don't want me to use doc librairie especially done for that. You can't tell that it's because of me. ,I don't even have to set settings.role to test in a test to be sure that it works. I only need it to make server run on local machine.

So Jeff, I do things carefully and I think a lot before doing anything. And it is not because I am younger than you in this job that I always do bad things and I'm stupid. I am smarter than you might think and I know what I do

**Comment by JeffAbrahamson** [comment]
Did you read commit `origin/jeff-settings-test` (f28a28dfcfdb2fe40fffca21a28290003d379f8b) that sent you the other day to illustrate this?

Did you have the slightest idea what I might be talking about with the `setUp()` function?  Try to figure it out, if it wasn't absolutely blatantly obvious.  You've had a few _days_ to think this through.

**Comment by Qlexio** [comment]
@JeffAbrahamson 
I understand `setUp()` function as a function setting up values inside before each test.
So, I've change test code and tried with and without `setUp()` and even with different values inside.
I've even part of test code that might make it so noisy but nothing changes

**Comment by JeffAbrahamson** [comment]
That is far too vague for any sort of response.

You should push a clearly-named branch with a clearly explained [reprex](https://stackoverflow.com/help/minimal-reproducible-example), indicating what you did, what you expect, and what happened.

**Comment by Qlexio** [comment]
@JeffAbrahamson 
I pushed changes to branch `origin/login_by_mail_2`.
The only changes are about test.py where I add `setUp()` as suggestion and remove every explicite call to `views.login()` function that might cause the noise when testing.

**Comment by Qlexio** [comment]
I forgot to tell you that I noticed that every `print()` of the code, wherever it is wroten, is printed in console when run tests.
And as `request = self.client.post(reverse("authentication:login"), context)` implicitly calls `authentication.views.login`, it also calls `print('ObjectDoesNotExist')` on line 52 because `user.refresh_from_db()` on line 47 seems to fail everytimes and it is the same for `send_activation()`.
