### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by Qlexio** [transport-nantes/tn_web#83]
@JeffAbrahamson 
I have thought of two ways to manage users account deletion:

1. I create a new models in which I move email, username, and so on of user when he wants to delete his account and I remove those informations from `auth.models.User`. This way `User.objects.count()` will give you registered users and `new_model.objects.count()` will give you deleted ones. This allows you to easily make statistics and you keep user informations. Also, like users are not anymore in `auth.models.User`, they can register again with the same mail. It allows you to see the number of users deleting accounts then register again and how many times too.
2. Another way is to create a model with user foreign key as pk and add a boolean field set to True by default when registering or false if deleted. It means to change `authentication.views.login` to allow users to register again with the same mail if account is considered as deleted. As `auth.models.User` allows to have the same email many times, it should work. This option may make statistics a little bit harder but it's just a supposition with my actual knowledge.

In both ways, we don't have to keep informations as well. We can change them if needed but you wouldn't be able to see which user deleted his account.

**Comment by JeffAbrahamson** [comment]
Option (1) will break relational integrity and/or cause cascading deletes.  Don't do it.

I don't understand option(2), but it doesn't sound right.

What you should do is this:
1. Load the user.  Set user.email, user.first_name, and user.last_name, and user.password to `get_random_string(15)` (a new call each time, of course).
2. Set `user.is_active = False`
3. Set `user.is_staff = False`
4. Set `user.is_superuser = False`
5. Save the user object without commit
6. Look at the MalingListEvent object in `mailing_list/models.py`
7. Create a similar model in `authentication/models.py` called AuthEvents with events create and delete.
8. Write a delete event for the user.
9. Save and commit

Look at `mailing_list/views.py` to see one way to do this.

**Comment by JeffAbrahamson** [comment]
See [django.contrib.auth docs](https://docs.djangoproject.com/en/3.1/ref/contrib/auth/) if you haven't already.
