### ISSUE TITLE
send record dashboard

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#836]
While we're in dashboard mode, let's make a first draft of this one.

* Tabs or something similar to choose marketing or transactional and their subtypes.
* Sort by first activity (first handoff timestamp) DESC
* For marketing,
  * group by slug
  * Data per row: time of first handoff, time of last activity, total #, %handoff, %send-confirmed, %opened, %clicked.
* For transactional, 
  * Each record on one line
  * Times present if exist (with offset indicated from handoff time), blank if NULL.

To keep in back of head: would be nice to have some day sorted by last activity as an option.

This should be easily readable and responsive but still efficient with its use of screen real estate: it is an admin dashboard.

**Comment by Shriukan33** [comment]
Duplicates #870
