### ISSUE TITLE
Verity that all tnmd operations render in email

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#840]
Because the CTA didn't.  ;-)

**Comment by Shriukan33** [comment]
Should CTA buttons render MD ?  Like the label ?

**Comment by JeffAbrahamson** [comment]
The markdown engine identifies requests for html and, for TN-specific items, calls functions that render it.  Those functions consult the context to determine if they are in email or on the web, then emit the appropriate html for that context.

The CTA does not render nicely in email.  It should.
