### ISSUE TITLE
Apply corporate identity and style guide to buttons in mobilito

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#875]
The corporate identity and style guide can be found in our Drive : https://drive.google.com/file/d/1XWZuei6EHn0KQLnfFhAn-g_RixLX3Hr8/view

Currently, buttons use the same colors as Mobilitains, but the style onlick is simply a lighter color, instead of color inversion like we do in the website : 

https://user-images.githubusercontent.com/70256364/183414949-8fb784d5-ad18-4094-84d7-cf71eb90aa93.mp4

![mobilito-btn-onlick-hover](https://user-images.githubusercontent.com/70256364/183417372-ed8e71e6-172f-469e-8597-ec876f455609.gif)

**Comment by JeffAbrahamson** [comment]
What is the status of this issue?
