### ISSUE TITLE
Add proper 404 handling for TB

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#888]
Rollbar has been emailing us about bots that fail to find non existent pages.

We should patch these so Rollbar doesn't notify us about bots being bots.

**Comment by JeffAbrahamson** [comment]
How do you know they are bots?

**Comment by Shriukan33** [comment]
> How do you know they are bots?

Browser names are GoogleBot and BingBot

https://rollbar.com/mobilitains/all/rql/?enc_q=4OFkT06g3xgrTdIcR4bJ6RLVGn%2Bl6K0r2aQJgsTiTGBQ8wr6RQyFDfwrrjs4lsFB675Dd98BmmoNMFX9wiHILjqcfqqez79%2F7W2D7rixbwJo6DQLEf5aVB%2FEYfPx0vHvENZCRNEazxcqVUAZcE8w7BW9cKR6Wv40%2BokeMp5b0Y5qKA0BAApv5AIZFbrmts3s&projects=573025

**Comment by Shriukan33** [comment]
So I took a look at the Docs from Rollbar to see if there was a filter option for bots, as I don't want to ignore 404 from actual users (which may indicate we have dead links for example)

I found this : https://docs.rollbar.com/docs/filter-or-ignore-errors-from-bots

And managed to build a config file that filters the two bots that have been raising errors until now, you can find it there : 
https://rollbar.com/mobilitains/tn-prod/settings/custom_fingerprinting/#custom-grouping-form

If any other bot ends up raising errors, it needs to be added in this filter.

Apparently, it groups bots errors into a single item, that we can mute / adjust severity.
Best solution I could find so far.
