### ISSUE TITLE
Add information about data usage

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#893]
With Mobilito, we collect data. User aren't informed about their usage, it might be wise to tell them why they should measure modal share. 

I'm not exactly clear where and what we should say about that.

**Comment by Shriukan33** [comment]
@JeffAbrahamson  I'd like your input on that

**Comment by JeffAbrahamson** [comment]
Eventually we should say something more explicit.  It falls into the category of encouraging users to participate, why they should do that.  We currently have no users, so it's not urgent.  The first users must be standing next to us, and hearing their questions and comments will inform what we write on such a page.

The technical side of it is covered by our privacy policy, so from a legal standpoint we're ok.
