### ISSUE TITLE
Fetch and use more OG data in presse mentions

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#901]
I think we should fetch more OG data (and use it, unless the user overrides).  And we should do this as soon as we have the URl, not encourage the user to fill out a form that we're going to auto-fill and ignore in a moment, after they hit "save".

So, a new pm asks you for URL (only).  Once you provide it and confirm, it does the OG fetch, makes things like journal name, article title, and article description be copies of what it found in OG, saves that, and displays the pm as a view-one.  Click to edit.

There's an open question whether we should go to view-one or edit-one at that step two.  It will depend on experience, on whether it's rare or common that the OG data doesn't suffice.

It's especially frustrating that journal title, article title, and article description or mandatory, and yet all three can generally be fetched from OG data.

**Comment by JeffAbrahamson** [comment]
I provided only the URL:
![image](https://user-images.githubusercontent.com/1220683/186594991-fa06f486-f163-42cc-8519-51af2eb9db13.png)

But I could have had this (the OG pre-visualisation):
![image](https://user-images.githubusercontent.com/1220683/186595085-ee40b078-9b23-462c-b634-041da26207df.png)

**Comment by JeffAbrahamson** [comment]
I presume y'all regularly look at OG data given that you've been working with it, but just a reminder, there's a lot of it.
 ```
<meta property="og:locale" content="fr_FR">
<meta property="og:site_name" content="Presse Océan">
<meta property="og:title" content="Transports en commun à Nantes : vers une grève à la rentrée ? | Presse Océan">
<meta property="og:url" content="https://www.ouest-france.fr/pays-de-la-loire/nantes-44000/transports-en-commun-a-nantes-vers-une-greve-a-la-rentree-0a1f141e-23a6-11ed-8f1c-0ca1882e16aa">
<meta property="og:type" content="article">
<meta property="og:description" content="[Presse Océan] Les syndicats de la société de transports en commun de l’agglomération nantaise (Semitan) viennent de déposer, ce mercredi 24 août, une alarme sociale. Une première étape avant une possible grève à la rentrée. Une rencontre est prévue lundi 29 août avec la direction.">
<meta property="fb:page_id" content="283715565807">
<meta property="og:image" content="https://media.ouest-france.fr/v1/pictures/MjAyMjA4ZGUwMjZjZTMzMDhmZDdlZmMyMmQyYzVmMjNjNDAyNmM?width=1260&height=708&focuspoint=50%2C25&cropresize=1&client_id=bpeditorial&sign=caae5bd30a52ec5d28a87376c795742011bae14066606448fa0bd2cd6629e7c0">
<meta property="og:image:height" content="708">
<meta property="og:image:width" content="1260">
<meta property="article:author" content="Presse Océan">
<meta property="article:section" content="Nantes">
<meta property="article:tag" content="Nantes">
<meta property="article:tag" content="Transports">
<meta property="article:tag" content="Business, Finance, & Economics">
<meta property="article:tag" content="Une">
<meta property="article:tag" content="Loire-Atlantique">
<meta property="article:published_time" content="2022-08-24T14:39:19Z">
<meta property="article:modified_time" content="2022-08-24T14:39:19Z">
<meta property="article:content_tier" content="free">
<meta property="article:location" content="city:Nantes,Loire-Atlantique">
```

And there's a spec: [ogp.me](https://ogp.me/).

**Comment by Shriukan33** [comment]
Didn't you specified that we should by default use OG data, and when absent, use user's input ? Because that's what it does iirc ?

The form is sort of a fallback basically, if OG is unavailable.

**Comment by JeffAbrahamson** [comment]
Yes, but we also are _requiring_ the user to enter data that we are _planning_ on not using.  That's not polite of us.
