### ISSUE TITLE
Clean up /d/ dashboard

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#907]
The `/d/` page is messy.  We should make a clean table that explains (briefly) what things are, uses correct internal names, and uses standard icons to indicate displaying a list view or creating a new entry.

We should obviously not offer to show people things they aren't allowed to see.

**Comment by Shriukan33** [comment]
Duplicate #831, I've a branch coming. 

Did a table, just need to add the permission check.
