### ISSUE TITLE
The "Je me localise" button doesn't localise me

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#917]
It just displays the map.

In addition, it's not (currently) providing "localisation", which is mandatory but shouldn't be, because the user must not be required to provide geo data at all.  (It's a brake on usage.)

**Comment by Shriukan33** [comment]
So I checked this one, it seems to have to do with API Key configuration :
![image](https://user-images.githubusercontent.com/70256364/192224736-08449ae6-0103-4d48-8ad7-91219fa770d8.png)

It doesn't get an address in response so no marker is placed.

**Comment by JeffAbrahamson** [comment]
What key are you using?

**Comment by JeffAbrahamson** [comment]
Is something being logged that we somehow missed?

**Comment by Shriukan33** [comment]
> What key are you using?

This is beta.mobilitains.fr
