### ISSUE TITLE
Create a session summary page

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#927]
Initially, it's pretty much the same as the summary mail.

If the session is auth'd to the same user id as did the recording, then show the session summary regardless of the following.

If not, then only show if all of the following are true:
* The session auth timestamp is set.
* The session has closed.
* The session published boolean is set (field to add in this issue).

Initially, we'll set the published flag to `True` by default.  It's a way for us to take stuff offline quickly if we find some abuse.  Planning ahead.

**Comment by Shriukan33** [comment]
Question about the URL path here : 
- Should we make the most basic URL with /mobilito/session/<id> with <id> being the object's database ID (Integer) ?
- From where do you access this link ? E-mail only or a dedicated page ?
- If I understand this correctly, you can actually share the session with anyone as long as it matches the 3 criteria (if you're not the author). Does the author still access their session if we toggle the published field to off ?
- We could use UUID to make URLs (to avoid db mapping with bruteforce), if we make it a primary key, we can either erase all data or we could do some gymnastic to transfer the id from id to uuid and the re-set foreign keys (https://blog.hexack.fr/en/change-the-primary-key-of-a-django-model.html)

**Comment by Shriukan33** [comment]
> Question about the URL path here :
> 
>     * Should we make the most basic URL with /mobilito/session/ with  being the object's database ID (Integer) ?
> 
>     * From where do you access this link ? E-mail only or a dedicated page ?
> 
>     * If I understand this correctly, you can actually share the session with anyone as long as it matches the 3 criteria (if you're not the author). Does the author still access their session if we toggle the published field to off ?
> 
>     * We could use UUID to make URLs (to avoid db mapping with bruteforce), if we make it a primary key, we can either erase all data or we could do some gymnastic to transfer the id from id to uuid and the re-set foreign keys (https://blog.hexack.fr/en/change-the-primary-key-of-a-django-model.html). Wdyt ?

**Comment by JeffAbrahamson** [comment]
> Question about the URL path here :
> 
>     * Should we make the most basic URL with /mobilito/session/ with  being the object's database ID (Integer) ?

No, because we don't want to reveal things like how much people use the service, how many observations there are, etc.



>     * From where do you access this link ? E-mail only or a dedicated page ?

How people find the link is a different PR.  This PR is about making the page.

We'll use it in mails, in social media, etc.

 
>     * If I understand this correctly, you can actually share the session with anyone as long as it matches the 3 criteria (if you're not the author). Does the author still access their session if we toggle the published field to off ?

Creator and admins can always see.
If admin, we note that it's invisible.  If user, we don't.


>     * We could use UUID to make URLs (to avoid db mapping with bruteforce), if we make it a primary key, we can either erase all data or we could do some gymnastic to transfer the id from id to uuid and the re-set foreign keys (https://blog.hexack.fr/en/change-the-primary-key-of-a-django-model.html). Wdyt ?

We don't want to make our primary keys be UUID's.  That's a rather big project and we don't have bandwidth for it.

It also presents potential performance issues if UUID's are represented as strings, since strings take more CPU to sort, take more space in memory, sorting requires paying attention to locale, it introduces encoding issues, etc.

**Comment by Shriukan33** [comment]
> > Question about the URL path here :
> > ```
> > * Should we make the most basic URL with /mobilito/session/ with  being the object's database ID (Integer) ?
> > ```
> 
> No, because we don't want to reveal things like how much people use the service, how many observations there are, etc.
> 
> > ```
> > * From where do you access this link ? E-mail only or a dedicated page ?
> > ```
> 
> How people find the link is a different PR. This PR is about making the page.
> 
> We'll use it in mails, in social media, etc.
> 
> > ```
> > * If I understand this correctly, you can actually share the session with anyone as long as it matches the 3 criteria (if you're not the author). Does the author still access their session if we toggle the published field to off ?
> > ```
> 
> Creator and admins can always see. If admin, we note that it's invisible. If user, we don't.
> 
> > ```
> > * We could use UUID to make URLs (to avoid db mapping with bruteforce), if we make it a primary key, we can either erase all data or we could do some gymnastic to transfer the id from id to uuid and the re-set foreign keys (https://blog.hexack.fr/en/change-the-primary-key-of-a-django-model.html). Wdyt ?
> > ```
> 
> We don't want to make our primary keys be UUID's. That's a rather big project and we don't have bandwidth for it.
> 
> It also presents potential performance issues if UUID's are represented as strings, since strings take more CPU to sort, take more space in memory, sorting requires paying attention to locale, it introduces encoding issues, etc.

So can we just go with uuid to access the session, but it's not the ID then ? it hides the number of session issue, how many observation there are etc
We would essentially filter using uuid to make a query.

**Comment by JeffAbrahamson** [comment]
Either we use a [hashid](https://hashids.org/) or a UUID or sha254 etc.  In any case, we need an extra column to store it, and that column must have a unique constraint to keep us honest.

Something like a hashid has the advantage of being relatively short but still unique.  UUID's are a bit unsightly to non-devs.

An alternative that doesn't require a new dependency is to do a cryptographic hash (e.g., sha256) something like this:
```
now = time.monotonic_ns()
hashlib.sha256(f"{now}|{user_id}|{pk_id}".encode("utf-8")).hexdigest()
```
or even the somewhat shorter
```
hashlib.sha1(f"{now}|{user_id}|{pk_id}".encode("utf-8")).hexdigest()
```
I don't think we need to worry about SHA1 vulnerabilities here, since constructing collisions is not an interesting attack.

I'm leaning towards favoring this last.
