### ISSUE TITLE
Brand mobilito better

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#964]
All of mobilito should follow the same branding:
* title should say "Mobilito: un projet des Mobilitains"
* that should be a single string so that we can change it as we think of better
* background should always be mobilitains-bleu-fonce
* text should always be white
* logo should always be M-logo-white.png

This includes the emails we send for mobilito.

**Comment by Shriukan33** [comment]
Maybe this could all be a base template for Mobilito, one place that defines background color (css), title (html)
