### ISSUE TITLE
Create TbEmailPanel

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#978]
We want a TB object that we can insert into emails (and so also renders on web pages, when that is appropriate to the email object).  We'll insert it into emails with a template tag available via markdown.  The markdown support is a separate issue.

Adding new TB types should be quick and easy at this point.  If it takes longer than two hours to add the new TB type or more than another two hours to create the tag, we should document why this is so that we can correct our design.  Almost all the functionality lives in the base classes, so making new types should be a short bit of bookkeeping.

**Comment by Shriukan33** [comment]
What do you mean by "can be inserted into emails" ? Do you have an example ?

**Comment by JeffAbrahamson** [comment]
I'm writing a mail and I insert some bit of image + text thus `{% tb_email_panel 'my-panel-text' %}`.

**Comment by Shriukan33** [comment]
From slack conversation, here for documentation :

First template idea, though not the only one : 
![image](https://user-images.githubusercontent.com/70256364/200604075-4ccf9e6b-247c-47bd-84a8-49dc619be782.png)


> * While writing a TBEmail, I should be able to write in one of the Markdown field (ex: body_text_1_md) `[[tbepanel]]((arg1))` and the result would be an image on the left and a text on the right with a "Le saviez-vous ?" title above it. arg1 would be the slug corresponding to the desired panel (ex: "ped-tip-1")
> 
> * You can also use a template tag  {% tbepanel 'ped-tip-1' %} in templates
> 
> * The tbepanel should render equally on web and on emails
> 
> * Tbepanels should be published before being able to be used. (TB style)
