### ISSUE TITLE
Can we bump to django 4.1.x?

### ISSUE THREAD

**Issue by JeffAbrahamson** [transport-nantes/tn_web#983]
Are there any blocking issues?

**Comment by Shriukan33** [comment]
The only thing I could find in the changelog would be an incompatibility between django 4.1 and asgiref==3.4.1 in our requirements.txt

Sadly, pip doesn't handle dependencies updates and compatibility contrary to poetry for example :disappointed: 
I will see to update those two packages first and see what's happening
