### ISSUE TITLE
Make a public ListView for photo contest 

### ISSUE THREAD

**Issue by Shriukan33** [transport-nantes/tn_web#986]
I'm seeing it as a gallery with rows of 3 photos, and about 3 photo tall (above the fold you should see about 9 photos) 
Clicking on any of them will lead to the detail view where you can vote, as introduced in #963 

Only accepted photos are displayed.

**Comment by JeffAbrahamson** [comment]
How very web 2.0.

Twenty years on would be with infinite scroll.
e.g., [WPY](https://www.nhm.ac.uk/wpy/gallery)

I don't know what's involved in making that happen, however.  Is it feasible?
Or perhaps we could fake it, knowing that we will only have 10-20 photos all told?

**Comment by Shriukan33** [comment]
> I don't know what's involved in making that happen, however. Is it feasible?

I don't know what you mean by "it"

Do you mean loading images as user scroll down ? Or simply paginate ?
I can certainly make the photo bigger and be a 2 photo wide gallery

I'm prototyping atm, it looks like this 
![image](https://user-images.githubusercontent.com/70256364/200281223-3386293a-17fd-4e14-828c-2fff79b233a8.png)

**Comment by JeffAbrahamson** [comment]
https://duckduckgo.com/?t=ffab&q=infinite+scroll&atb=v345-1&ia=web

**Comment by JeffAbrahamson** [comment]
But we have so few images, it would make more sense just to display them all rather than go to much effort to get infinite scroll working.  Unless infinite scroll turns out to be really easy to do.  Time box it.
